apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-github-test4
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rh-ee-lyoon-dh/chatbot-github-test4:6268886f993cd969da56a356f80636588c12a2c9@sha256:3021b240943868e59c09ef0a00fc2791aefe57160717b6215e08a6ac728a9e30 # use pre-built to bootstrap
          name: app-inference
